test automation pipeline

diff --git a/.github/workflows/test_automation.yml b/.github/workflows/test_automation.yml
--- a/.github/workflows/test_automation.yml
+++ b/.github/workflows/test_automation.yml
@@ -58,13 +58,15 @@ jobs:
           echo "Waiting for application to be ready at ${{ env.url }} "
           max_attempts=10
           attempt=1
+
+          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }} || { echo "Azure login failed"; exit 1; }
+          TOKEN=$(az account get-access-token --resource ${{ env.url }} --query accessToken -o tsv)
           
           while [ $attempt -le $max_attempts ]; do
             echo "Attempt $attempt: Checking if application is ready..."
-            if curl -f -s "${{ env.url }}" > /dev/null; then
+            if curl -f -s -H "Authorization: Bearer $TOKEN" "${{ env.url }}/api/test" > /dev/null; then
               echo "Application is ready!"
               break
-
             fi
             
             if [ $attempt -eq $max_attempts ]; then
